### ISSUE TITLE
Add Rss

### ISSUE THREAD

**Issue by leonardootto** [alimate/alimate.github.io#1]
Hello.
I really use a lot of rss feeds and feed aggregators.
May you please add rss to you personal blog?

Thanks.

**Comment by alimate** [comment]
@leonardootto Thanks for your feedback. This issue resolved with [this commit][1]. Sorry it took me so long to fix it. https://alidg.me/feed.xml

[1]: https://github.com/alimate/alimate.github.io/commit/0fe49eaacea7eb18b8e6afa3c4dc5541dff1e842
